slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: '#lower-priority-alarms'
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: 'Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title: '$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title_link: 'https://concourse.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME'
  footer: concourse.cloud-platform.service.justice.gov.uk/

resources:
- name: orphaned-namespace-checker-image
  type: docker-image
  source:
    repository: registry.hub.docker.com/ministryofjustice/orphaned-namespace-checker
    tag: 2.18
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/((slack-hook-id))
- name: every-week
  type: time
  source:
    # one week in hours
    interval: 168h

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

groups:
- name: live-1
  jobs: [check-live-1]

jobs:
- name: check-live-1
  serial: true
  plan:
    - aggregate:
      - get: every-week
        trigger: true
      - get: orphaned-namespace-checker-image
    - task: check-environments
      image: orphaned-namespace-checker-image
      config:
        platform: linux
        params:
          KUBECONFIG_AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
          KUBECONFIG_AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
          KUBECONFIG_AWS_REGION: eu-west-2
          KUBECONFIG_S3_BUCKET: cloud-platform-concourse-kubeconfig
          KUBECONFIG_S3_KEY: kubeconfig
          KUBE_CTX: live-1.cloud-platform.service.justice.gov.uk
          KUBE_CONFIG: /tmp/kubeconfig
          KUBERNETES_CLUSTER: live-1.cloud-platform.service.justice.gov.uk
          TFSTATE_AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
          TFSTATE_AWS_REGION: eu-west-1
          TFSTATE_AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
          TFSTATE_BUCKET: cloud-platform-terraform-state
          TFSTATE_BUCKET_PREFIX: cloud-platform-environments/live-1.cloud-platform.service.justice.gov.uk
          GITHUB_TOKEN: ((cloud-platform-environments-pr-git-access-token))
        run:
          path: /app/bin/orphaned_namespaces.rb
        outputs:
          - name: output
      on_success:
        put: slack-alert
        params:
          <<: *SLACK_NOTIFICATION_DEFAULTS
          text_file: output/check.txt
      on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
